export const users = [{
    "id": 1,
    "name": "Drona",
    "age": "32",
    "email": "dreeks0@cornell.edu",
    "country": "Mexico",
    "company": "Jabberbean",
    "birthday": "26/02/1990"
  }, {
    "id": 2,
    "name": "Gillian",
    "age": "30",
    "email": "gteers1@usatoday.com",
    "country": "Poland",
    "company": "Zoonder",
    "birthday": "26/10/1991"
  }, {
    "id": 3,
    "name": "Bessie",
    "age": "41",
    "email": "bbendan2@house.gov",
    "country": "Philippines",
    "company": "Divavu",
    "birthday": "20/08/1980"
  }, {
    "id": 4,
    "name": "Jerald",
    "age": "23",
    "email": "jjex3@foxnews.com",
    "country": "China",
    "company": "Brainsphere",
    "birthday": "19/07/1998"
  }, {
    "id": 5,
    "name": "Simon",
    "age": "35",
    "email": "ssammonds4@miitbeian.gov.cn",
    "country": "Sri Lanka",
    "company": "Kwimbee",
    "birthday": "23/12/1986"
  }, {
    "id": 6,
    "name": "Alric",
    "age": "29",
    "email": "alantuffe5@geocities.com",
    "country": "China",
    "company": "Realbuzz",
    "birthday": "11/10/1992"
  }, {
    "id": 7,
    "name": "Aile",
    "age": "27",
    "email": "astarford6@baidu.com",
    "country": "China",
    "company": "Twimbo",
    "birthday": "20/07/1994"
  }, {
    "id": 8,
    "name": "Sean",
    "age": "35",
    "email": "smathie7@rambler.ru",
    "country": "China",
    "company": "Centizu",
    "birthday": "18/05/1987"
  }, {
    "id": 9,
    "name": "Robby",
    "age": "27",
    "email": "rkleinpeltz8@indiegogo.com",
    "country": "Indonesia",
    "company": "Agimba",
    "birthday": "26/07/1994"
  }, {
    "id": 10,
    "name": "Luca",
    "age": "32",
    "email": "larbon9@digg.com",
    "country": "China",
    "company": "Centizu",
    "birthday": "25/01/1992"
  }]